### ISSUE TITLE
[question] How to use the externally installed llvm?

### ISSUE THREAD

**Issue by yurivict** [emscripten-core/emscripten-fastcomp#260]
This project seems to rebuild the LLVM codebase when I already have llvm6, llvm7 and llvm8 installed.

How to make emscripten to use the preinstalled llvm?

**Comment by kripken** [comment]
Installing using the emsdk will get you binaries, have you tried that? Alternatively, you can edit the `.emscripten` file in your home directory to point to one of your installed LLVM's binary directories.

**Comment by yurivict** [comment]
I don't want binaries, I need everything to be installed from sources on FreeBSD.

> Alternatively, you can edit the .emscripten file in your home directory to point to one of your installed LLVM's binary directories.

Are there instructions how to install this way? I guess I don't need ```emscripten-core/emscripten-fastcomp``` then?

**Comment by sbc100** [comment]
Emscripten supports two versions of llvm.  `emscripten-fastcomp` is the current default and you won't find that in FreeBSD (at least I don't think you will) because its a custom fork of llvm.    If you want to use that you can build it from source, or you and use emsdk to get prebuilt binaries.   Building it form source needs to be done by hand.  It pretty well documented: https://emscripten.org/docs/building_from_source/building_fastcomp_manually_from_source.html

If you want to use llvm upstream instead will need the very latest version llvm8 may work but really you need the current ToT (perhaps there is an llvm-preview or latest package in FreeBSD).  The reason is that we are developing the new backend upstream and oftern use the very latest features as they lan in llvm.  All you need to do to use it is modify your `.emscripten` file to point to you version of LLVM.

**Comment by yurivict** [comment]
The problem with ```emscripten-fastcomp``` is that it installs llvm info ```$PREFIX``` ad conflicts with some other software that installs their own llvm forks there.
----
I am trying to create a FreeBSD port for emscripten, but I am not sure how to build it.
The Arch Linux port seems to check out all repositories, and then they just run cmake: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emscripten-git

But ```CMakeLists.txt``` only exists in ```emscripten-fastcomp```. So Arch seems to build only the custom LLVM version?

How to build emscripten using the externally installed LLVM version?

**Comment by sbc100** [comment]
You can have fastcomp install whereever you prefer using the `-DCMAKE_INSTALL_PREFIX=` cmake flag.

To choose which version of llvm emscripten use modify the "LLVM" variable in your `.emscripten` file.   Normally this lives in the users `$HOME` directory.. so each user would decide which LLVM to use.

However for this kind of packaging you might want some kind of global configuration that works for all users.   In that case you could create shared config file and specify that using the EM_CONFIG environment variable.      On example of doing that is here: 
https://github.com/WebAssembly/waterfall/blob/master/src/emcc_wrapper.sh

**Comment by sbc100** [comment]
Yes it looks like arch alwasy uses fastcomp.  See LLVM_ROOT in  https://aur.archlinux.org/cgit/aur.git/tree/emscripten.config?h=emscripten-git

This is not surprising since its still the primary and default compiler for emscripten. 

We are planning on moving away from it soon, but the transition has not happened yet.

**Comment by yurivict** [comment]
What do I need to do to build with the external llvm?

**Comment by sbc100** [comment]
Emscripten itself has not "build" process per-say, it just a python driver for LLVM.

All you need to do is configure emscripten at runtime via the config file to point the LLVM version you want to use.

**Comment by yurivict** [comment]
I installed ```emscripten``` on FreeBSD. It is using the latest ```LLVM``` from the package ```llvm-devel``` which is at version 9.x. I appended ```-devel``` to all executable named in ```tools/shared.py``` because that's how these executables named on BSD.

However, ```emcc``` fails:
```
$ emcc 
shared:WARNING: LLVM version appears incorrect (seeing "9.0", expected "6.0")
shared:CRITICAL: fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
```

Why does it expect version ```6.0```? (You said above that ```emscripten``` works with the very latest llvm version. It is now 9.)

**Comment by yurivict** [comment]
It works, thank you for your help!
