### ISSUE TITLE
llvm.fma

### ISSUE THREAD

**Issue by sunfishcode** [emscripten-core/emscripten-fastcomp#83]
Clang eagerly turns fma and fmaf calls into llvm.fma.f32 and llvm.fma.f64 intrinsics, since these functions are defined to never set errno. Emscripten currently doesn't implement these intrinsics, so code using fma and fmaf gets undefined references to llvm.fma.f32 and llvm.fma.f64.

The most obvious fix, adding entries to lib/Target/JSBackend/CallHandlers.h to expand them to plain _fma and _fmaf calls, doesn't appear to work. The calls get rewritten, but the module still appears to declare dependencies on llvm_fma_f32 and llvm_fma_f64.

**Comment by juj** [comment]
Would you happen to have a test case that shows the failure with this?

**Comment by sunfishcode** [comment]
```
#include <math.h>

volatile float f;
volatile float g;
volatile float h;
volatile float i;

int main()
{
    i = fmaf(f, g, h);
    i = fma(f, g, h);
    return 0;
}
```

Emscripten says:

warning: unresolved symbol: llvm_fma_f64
warning: unresolved symbol: llvm_fma_f32

**Comment by kripken** [comment]
Is it just a warning, but the right code is emitted? If so, we just need to suppress the warning by adding a stub in `src/library.js` (see `misc definitions to avoid unnecessary unresolved symbols from fastcomp`)

**Comment by diplojocus** [comment]
In our case the llvm_fma_f32 function is not generated and it breaks the emitted code.

**Comment by kripken** [comment]
I think we need to test that with the changes to `CallHandlers.h` that @sunfishcode mentioned - are they pushed to incoming?

**Comment by sunfishcode** [comment]
They are not yet in incoming. I didn't want to check anything in until I had something which actually worked. With the changes to ```CallHandlers.h``` and stubs in ```src/library.js```, I appeared to get the problem that the the real _fma and _fmaf were not actually linked in anymore, so I ended up with undefined references to those symbols.

**Comment by kripken** [comment]
Looking into this some more and talking with @sunfishcode , the following are concerns:

1. fma and fmaf are going to be slow. It would be best not to surprise people, because natively they might be very fast. The slowness comes from the inability to use low-level CPU instructions, at least for now.
2. The musl implementation of fmaf uses floating-point exceptions, which we don't support. So we don't have an way to get a correct but slow solution here.
3. There is also an emscripten build system issue - we depend on `llvm-nm` to tell us which symbols are undefined, and pull in system libs accordingly. Turns out `llvm-nm` reports all `declare`s, *except* for intrinsics like `llvm.fma.f64`, which means we miss them. To get around that, we'd need to run something more than `llvm-nm` at an early stage in the process.

The last issue seems like a significant amount of work that given the first two issues, maybe we don't want, at least for now.

**Comment by kripken** [comment]
(We could work around the third issue if we told LLVM to not transform fma/fmaf calls into LLVM intrinsics, I don't know if there is a nice way to do that.)

**Comment by jevinskie** [comment]
-fno-builtin to clang prevents emission of llvm.fma.* but it also disables nice builtins like memset/memcpy.

**Comment by jevinskie** [comment]
You could also nuke out https://github.com/kripken/emscripten-fastcomp-clang/blob/master/lib/CodeGen/CGBuiltin.cpp#L1351-L1364

**Comment by piranna** [comment]
Any update on this? I have just bump with this issue too...

**Comment by sunfishcode** [comment]
The switch to the LLVM wasm backend might fix this. Also while here, `-fno-builtin-fmaf` / `-fno-builtin-fma` might be possible workarounds.

**Comment by wojdyr** [comment]
Is `-fno-builtin-fma` an option that one can specify somewhere, or an idea for the future?
